#ifndef CONSTANTESPARSER_H_
#define CONSTANTESPARSER_H_

#define TAM_MAX_POST 800000 // 100 kb
#define OK 0
#define NOMBRE_ARCHIVO_INVALIDO 1
#define CONTENT_LENGTH_EXCEDIDO 2
#define LONG_ENTRADA_ESTANDAR 160
#define BOUNDARY "boundary="
#define FILENAME "filename="
#define LARGO_MAX_BOUNDARY 30

#endif /*CONSTANTESPARSER_H_*/
